(()=>{
  const root=document.documentElement;
  const store=window.localStorage;
  const ACCENTS={blue:'#0b6cff',teal:'#0f9f94',orange:'#e58a00',violet:'#7c4dff',red:'#e34a5f'};
  function applyPrefs(){const mode=store.getItem('pwd_theme')||'system';const dark=mode==='dark'||(mode==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);root.dataset.theme=dark?'dark':'light';root.style.setProperty('--accent',ACCENTS[store.getItem('pwd_accent')]||ACCENTS.blue);root.style.setProperty('--font-scale',store.getItem('pwd_font_scale')||'1');const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=dark?'#07111f':'#f5f8fc'}
  applyPrefs();matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if((store.getItem('pwd_theme')||'system')==='system')applyPrefs()});window.PWDUI={applyPrefs,ACCENTS};
  function recents(){try{return JSON.parse(store.getItem('pwd_recent_tools')||'[]')}catch{return[]}}function track(a){const id=a.dataset.toolId,name=a.dataset.toolName,href=a.getAttribute('href');if(!id||!name||!href)return;let list=recents().filter(x=>x.id!==id);list.unshift({id,name,href,icon:a.dataset.toolIcon||'🛠️'});store.setItem('pwd_recent_tools',JSON.stringify(list.slice(0,8)))}document.addEventListener('click',e=>{const a=e.target.closest('a[data-tool-id]');if(a)track(a)});
  if(!document.querySelector('.fab-stack')&&document.body.dataset.pwdShell!=='off'){const s=document.createElement('div');s.className='fab-stack';s.innerHTML='<button class="fab secondary" id="pwdGuideFab" aria-label="Guide">💡</button><button class="fab" id="pwdCalcFab" aria-label="Calculator">🧮</button>';document.body.appendChild(s)}
  function makeSheet(id,title,body){let back=document.getElementById(id);if(back)return back;back=document.createElement('div');back.id=id;back.className='sheet-backdrop';back.innerHTML='<div class="sheet" role="dialog" aria-modal="true"><div class="sheet-handle"></div><h3>'+title+'</h3>'+body+'</div>';back.addEventListener('click',e=>{if(e.target===back)back.classList.remove('open')});document.body.appendChild(back);return back}
  let calcExpr='';function renderCalc(){const d=document.getElementById('pwdCalcDisplay');if(d)d.textContent=calcExpr||'0'}function calcPress(k){if(k==='C')calcExpr='';else if(k==='⌫')calcExpr=calcExpr.slice(0,-1);else if(k==='='){try{const clean=calcExpr.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replace(/(\d+(?:\.\d+)?)%/g,'($1/100)');if(!/^[0-9+\-*/().\s]+$/.test(clean))throw 0;const r=Function('"use strict";return ('+clean+')')();if(!Number.isFinite(r))throw 0;calcExpr=String(Number(r.toPrecision(12)))}catch{calcExpr='Error'}}else{if(calcExpr==='Error')calcExpr='';calcExpr+=k}renderCalc()}
  function openCalc(){const keys=['C','⌫','%','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','(',')','='];const buttons=keys.map(k=>'<button data-k="'+k+'" class="'+(k==='='?'eq':/[÷×−+%]/.test(k)?'op':'')+'">'+k+'</button>').join('');const back=makeSheet('pwdCalcSheet','Quick Calculator','<p>Fast arithmetic without leaving the current engineering screen.</p><div id="pwdCalcDisplay" class="calc-display">0</div><div class="calc-keys">'+buttons+'</div>');back.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>calcPress(b.dataset.k));back.classList.add('open');renderCalc()}
  function openGuide(){const back=makeSheet('pwdGuideSheet','PWD Tools Guide','<p>Type what you want to do. This first version routes you to the right tool offline.</p><div class="searchbox"><span>🔎</span><input id="pwdGuideInput" placeholder="e.g. convert units, route distance, retaining wall"></div><div id="pwdGuideResults" style="margin-top:10px;display:grid;gap:8px"></div>');const routes=[['convert unit pressure discharge velocity','Units','pwd_calculators_converters.html#unit'],['survey bearing wcb rb latitude longitude','Survey calculations','pwd_calculators_converters.html#civil'],['route chainage gps distance','Route & Chainage','pwd_route_distance_chainage.html'],['camera photo gps evidence','GPS Cam','pwd_gps_engineering_camera.html'],['retaining wall quantity section','Retaining Wall','pwd_retaining_wall_section_quantity.html'],['batch concrete material ajax','Batch','pwd_mix_batch_assistant.html'],['mix design concrete','Mix Design','pwd_concrete_mix_design.html'],['bridge hydraulic scour discharge','Bridge Hydro','bridge_hydraulic_calculator.html']];const input=back.querySelector('#pwdGuideInput'),out=back.querySelector('#pwdGuideResults');function render(q=''){const s=q.toLowerCase().trim();const list=s?routes.filter(r=>r[0].includes(s)||s.split(/\s+/).some(w=>w.length>2&&r[0].includes(w))):routes.slice(0,5);out.innerHTML=list.map(r=>'<a class="tool-row" href="'+r[2]+'"><span class="module-icon">→</span><span><b>'+r[1]+'</b><small>'+r[0]+'</small></span><span class="chev">›</span></a>').join('')||'<div class="page-note">No exact match yet. Try a simpler engineering word.</div>'}input.oninput=()=>render(input.value);render();back.classList.add('open');setTimeout(()=>input.focus(),80)}
  document.getElementById('pwdCalcFab')?.addEventListener('click',openCalc);document.getElementById('pwdGuideFab')?.addEventListener('click',openGuide);window.PWDUI.openCalc=openCalc;window.PWDUI.openGuide=openGuide;document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.sheet-backdrop.open').forEach(x=>x.classList.remove('open'))});
})();